language: python
python:
  - "2.7"

notifications:
      slack: gledev:BDwNaKy9PDs7g7zSd5c3cMxu

before_install:
  - wget https://s3.amazonaws.com/influxdb/influxdb_0.10.1-1_amd64.deb
  - sudo dpkg -i influxdb_0.10.1-1_amd64.deb
  - sudo /etc/init.d/influxdb start
  - sleep 8
install:
  - pip install -r requirements.txt
script: python test_api.py
